// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPtvG7fcv1V2WOOE3HNOjqixs8KbBBK4s',
    appId: '1:678445309288:web:2bc46d2f4e20ee89b88add',
    messagingSenderId: '678445309288',
    projectId: 'authtutorial-2062b',
    authDomain: 'authtutorial-2062b.firebaseapp.com',
    storageBucket: 'authtutorial-2062b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB26IliSDmrYIgEfT55f5X_NbGCnJb2bko',
    appId: '1:678445309288:android:b9632f9a5e5a740cb88add',
    messagingSenderId: '678445309288',
    projectId: 'authtutorial-2062b',
    storageBucket: 'authtutorial-2062b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2o1ibPSd8KRDylgTeTgBTbgolFOoKagg',
    appId: '1:678445309288:ios:e681f8e3afdec8d4b88add',
    messagingSenderId: '678445309288',
    projectId: 'authtutorial-2062b',
    storageBucket: 'authtutorial-2062b.appspot.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2o1ibPSd8KRDylgTeTgBTbgolFOoKagg',
    appId: '1:678445309288:ios:ec0241143582abc1b88add',
    messagingSenderId: '678445309288',
    projectId: 'authtutorial-2062b',
    storageBucket: 'authtutorial-2062b.appspot.com',
    iosBundleId: 'com.example.flutterAuth.RunnerTests',
  );
}
